name: map_upholders
description: "A new Flutter project."

version: 1.0.0+1

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter
    firebase_core: ^3.13.0
    firebase_auth: ^5.5.3
    cloud_firestore: ^5.6.7
    provider: ^6.0.5
    shared_preferences: ^2.1.0
    cupertino_icons: ^1.0.8
    google_sign_in: ^6.3.0
    flutter_secure_storage: ^9.2.4
    intl: ^0.20.2
    table_calendar: ^3.2.0
    image_picker: ^1.1.2
    record: ^6.0.0
    path_provider: ^2.1.5
    just_audio: ^0.10.3
    fl_chart: ^1.0.0
    flutter_local_notifications: ^19.3.0
    timezone: ^0.10.1
    audioplayers: ^6.5.0
    permission_handler: ^12.0.0+1
    http: ^1.4.0
    flutter_dotenv: ^5.2.1
    pdf: ^3.11.3
    printing: ^5.14.2
    share_plus: ^11.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    firebase_data_connect: ^0.1.0

flutter:
    uses-material-design: true

    assets:
        - .env
