// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBRVOJtHRM4TMLkHXvSmCPgK7n0KtcYUE',
    appId: '1:991480687197:web:1d93aa4b5f5c348ec1fbb4',
    messagingSenderId: '991480687197',
    projectId: 'upholder-moodtracker',
    authDomain: 'upholder-moodtracker.firebaseapp.com',
    storageBucket: 'upholder-moodtracker.firebasestorage.app',
    measurementId: 'G-1DL6NN6HC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIBqmPazJaWAeBy5pYhFzbYL0Pmqe3t-E',
    appId: '1:991480687197:android:ede76f7b90f26e65c1fbb4',
    messagingSenderId: '991480687197',
    projectId: 'upholder-moodtracker',
    storageBucket: 'upholder-moodtracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXbj5U0QDfErM9ev4TJQJYgbAa0LthOUU',
    appId: '1:991480687197:ios:3e179ecae85dbf45c1fbb4',
    messagingSenderId: '991480687197',
    projectId: 'upholder-moodtracker',
    storageBucket: 'upholder-moodtracker.firebasestorage.app',
    iosBundleId: 'com.example.mapUpholders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXbj5U0QDfErM9ev4TJQJYgbAa0LthOUU',
    appId: '1:991480687197:ios:3e179ecae85dbf45c1fbb4',
    messagingSenderId: '991480687197',
    projectId: 'upholder-moodtracker',
    storageBucket: 'upholder-moodtracker.firebasestorage.app',
    iosBundleId: 'com.example.mapUpholders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBRVOJtHRM4TMLkHXvSmCPgK7n0KtcYUE',
    appId: '1:991480687197:web:59478b57c2e9edd8c1fbb4',
    messagingSenderId: '991480687197',
    projectId: 'upholder-moodtracker',
    authDomain: 'upholder-moodtracker.firebaseapp.com',
    storageBucket: 'upholder-moodtracker.firebasestorage.app',
    measurementId: 'G-JCBY8K90D3',
  );
}
